### ISSUE TITLE
pre-train 모델을 받아볼 수 있을까요?

### ISSUE THREAD

**Issue by sooftware** [nawnoes/pytorch-meena#1]
pre-train 모델을 받아볼 수 있을까요?

**Comment by sooftware** [comment]
그리고 대화 데이터는 어떤 데이터를 사용했는지 알 수 있을까요?

**Comment by nawnoes** [comment]
안녕하세요~!

저도 아직 테스트 중이라 pretrain된 모델은 아직 없구

저의 경우는 대화 데이터는 별로 없어서 다른 언어모델처럼 학습 후 대화 데이터로 파인튜닝해서 테스트 해볼까 생각하고 있었습니다

감사합니다

**Comment by sooftware** [comment]
네 답변 감사합니다.
